# Generated by Django 2.2 on 2020-04-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mymail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('From', models.EmailField(max_length=254, verbose_name='cromarties2913@gmail.com')),
                ('To', models.EmailField(max_length=254)),
            ],
        ),
    ]
